C#_TAREAS_3ERO/8. WebApp_MDV_solucion/WebApp_MDV/Models/ErrorViewModel.cs
using System;

namespace WebApp_MDV.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

C#_TAREAS_3ERO/8. WebApp_MDV_solucion/WebApp_MDV/Controllers/CalculadoraController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp_MDV.Controllers
{
    public class CalculadoraController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Sumar( int numUno, int numDos )
        {
            ViewData["resultado"] = numUno + numDos;
            //int numUno = int.Parse(Request.Form["numUno"]);
            return View();
        }
    }
}

C#_TAREAS_3ERO/8. WebApp_MDV_solucion/WebApp_MDV/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApp_MDV.Models;

namespace WebApp_MDV.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

C#_TAREAS_3ERO/8. WebApp_MDV_solucion/WebApp_MDV/Controllers/MountainsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp_MDV.Controllers
{
    public class MountainsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

C#_TAREAS_3ERO/8. WebApp_MDV_solucion/WebApp_MDV/Views/Mountains/Create.cshtml
@model WebApp_MDV.Entidades.Mountain

<h4>Mountain</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Altitiud" class="control-label"></label>
                <input asp-for="Altitiud" class="form-control" />
                <span asp-validation-for="Altitiud" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

C#_TAREAS_3ERO/8. WebApp_MDV_solucion/WebApp_MDV/Views/Mountains/Index.cshtml
@model IEnumerable<WebApp_MDV.Entidades.Mountain>
@using WebApp_MDV.Entidades;

@{
    ViewData["Title"] = "Lista de montañas";
}

    <h1>@ViewData["Title"]</h1>

    <a class="btn btn-outline-dark mb-4" href="mountains/create">Registrar montaña</a>

    @if (!Model.Any())
    {
        <div class="alert alert-danger" role="alert">
            No hay montañas registradas
        </div>
    }
    else
    {

        <table class="table table-dark">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Altitud</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Mountain mountain in Model)
                {
                    <tr>
                        <td>@(mountain.Nombre)</td>
                        <td>@(mountain.Altitiud)</td>
                    </tr>
                }
            </tbody>
        </table>
    }

C#_TAREAS_3ERO/8. WebApp_MDV_solucion/WebApp_MDV/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp_MDV</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp_MDV</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculadora" asp-action="Index">Calculadora</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mountains" asp-action="Index">Montañas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApp_MDV - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>